name: kernel-adaptation-pine64 build

on:
  push:
    branches:
      - master
      - megi
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - megi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output

    - name: Build i486
      id: build_i486
      uses: coderus/github-sfos-build@master
      with:
        release: 3.4.0.22
        arch: i486

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: kernel-rpms
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
